AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is a SAM template for the flash-sam-lambda functionality

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  ExecEnv:
    Type: String
    AllowedValues:
      - local
      - dev
      - stage
      - prod
    Default: prod

Resources:
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: flask_api/
      Handler: app.app
      Runtime: python3.9
      Environment:
        Variables:
          REGION_NAME: !Ref AWS::Region
          EXEC_ENV: !Ref ExecEnv
      Policies:
      - Statement:
        - Sid: S3Permissions
          Effect: Allow
          Action:
          - s3:ListAllMyBuckets
          Resource: '*'
        - Sid: CloudWatchPermissions
          Effect: Allow
          Action:
          - "cloudwatch:GetMetricData"
          Resource: '*'
      Events:
        SayHello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
        FetchBuckets:
          Type: Api
          Properties:
            Path: /fetch-s3-buckets
            Method: get
        FetchSpecificCloudWatchMetrics:
          Type: Api
          Properties:
            Path: /fetch-specific-cloudwatch-metrics
            Method: get      
        FetchCloudWatchMetrics:
          Type: Api
          Properties:
            Path: /fetch-cloudwatch-metrics
            Method: post                     
  


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FlaskAPI:
    Description: "API Gateway endpoint URL for Prod stage for Flask SAM Lambda function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  FlaskFunction:
    Description: "Flask SAM Lambda Lambda Function ARN"
    Value: !GetAtt FlaskFunction.Arn
  FlaskFunctionIamRole:
    Description: "Implicit IAM Role created for Flask SAM Lambda function"
    Value: !GetAtt FlaskFunctionRole.Arn